### ISSUE TITLE
[Feat]: add css hover effect

### ISSUE THREAD

**Issue by Shon-TG** [schmelto/Portfolio#104]
### Feature request

Its good if u add some css hover effects In the porfolio

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by schmelto** [comment]
Nice idea! I will take care of that asap

**Comment by Shon-TG** [comment]
Nice!

**Comment by schmelto** [comment]
@Shon-TG do you meen by hover effect somethin similar than the badges [here](http://linkfree.eddiehub.org/) for the repositories etc in the portfolio?

**Comment by schmelto** [comment]
Closing this one. If you could elaborate this a little bit more feel free to reopen this
