### ISSUE TITLE
[Bug]: Lighthouse Check failing

### ISSUE THREAD

**Issue by schmelto** [schmelto/Portfolio#109]
### What happened?

https://github.com/schmelto/Portfolio/blob/main/.github/workflows/lighthouse.yml is failing due to changed URL see in https://github.com/schmelto/Portfolio/issues/100

### Relevant log output

![](https://img.shields.io/badge/Accessibility-0-red?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-0-red?style=flat-square) ![](https://img.shields.io/badge/Performance-0-red?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-0-red?style=flat-square) ![](https://img.shields.io/badge/SEO-0-red?style=flat-square) 
| Device | URL |
|--|--|
| mobile | https://schmelto.github.io/portfolio/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

GitHub Action Log can be found [here](https://github.com/schmelto/Portfolio/actions/runs/1241581152)

### What to do?

Update URL to ` https://schmelto.github.io/Portfolio/`

https://github.com/schmelto/Portfolio/blame/main/.github/workflows/lighthouse.yml#L18

**Comment by lem0n4id** [comment]
hey there, i would like to take up this issue

**Comment by schmelto** [comment]
@lem0n4id I assigned you feel free to open a PR for this issue.
