### ISSUE TITLE
[Feat]: Update Lighthouse Check to Version 4.0.0

### ISSUE THREAD

**Issue by schmelto** [schmelto/Portfolio#110]
### Feature request

https://github.com/marketplace/actions/lighthouse-check

```yml
- name: Lighthouse Check
  uses: foo-software/lighthouse-check-action@v4.0.0
```

### What to do?

Update https://github.com/schmelto/Portfolio/blame/main/.github/workflows/lighthouse.yml#L14 to
```yml
uses: foo-software/lighthouse-check-action@v4.0.0
```

**Comment by Jayita10** [comment]
Can I work on this issue?

**Comment by schmelto** [comment]
> Can I work on this issue?

Sure if you need any help please let me know
