### ISSUE TITLE
[Feat]: Custom Domain

### ISSUE THREAD

**Issue by FayasNoushad** [schmelto/Portfolio#151]
### Feature request

Add custom domain or github.io domain

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by schmelto** [comment]
Portfolio is accessible at https://schmelto.github.io/Portfolio/ do you mean that by github.io domain?

**Comment by FayasNoushad** [comment]
> Portfolio is accessible at https://schmelto.github.io/Portfolio/ do you mean that by github.io domain?

Yes

**Comment by FayasNoushad** [comment]
https://schmelto.github.io

**Comment by mjvbz** [comment]
Yes thats Good! Change the name of the repo to schmelto.github.io so this website will be visible at - https://schmelto.github.io

**Example: https://mjvbz.github.io**

Or else buy a custom domain and connect the Github pages to the domain. See for more info about custom domains - https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site
