### ISSUE TITLE
[Bug]: Remove GIF from Assets due not used anymore

### ISSUE THREAD

**Issue by schmelto** [schmelto/Portfolio#155]
Yes we could delete the gif in the assets folder but I would keep this another PR

_Originally posted by @schmelto in https://github.com/schmelto/Portfolio/issues/154#issuecomment-996558600_

**Comment by Evavic44** [comment]
Okay, I'll update it in the assets folder as well.

I need your help with something @schmelto. 
Please if you have the time, do check out this issue, thanks. https://github.com/CommunityPro/support/issues/5
