### ISSUE TITLE
[Bug]: Contrast on Light mode terminal

### ISSUE THREAD

**Issue by schmelto** [schmelto/Portfolio#198]
### What happened?

![image](https://user-images.githubusercontent.com/30869493/166562990-b6c2641c-ae27-463c-9cb5-cf288c8252eb.png)
![image](https://user-images.githubusercontent.com/30869493/166563110-e774021e-db48-49ba-8246-740efc39ead5.png)

**Comment by grlcodr** [comment]
Can I pick this one up? :)
