### ISSUE TITLE
[Bug]: Replace Twitter with X logo

### ISSUE THREAD

**Issue by schmelto** [schmelto/Portfolio#255]
Replace Twitter with X logo

<img width="977" alt="image" src="https://github.com/schmelto/Portfolio/assets/30869493/622ad3cb-b575-4466-a755-04614a181573">

maybe https://simpleicons.org/ could be used

**Comment by bilalshaikh292** [comment]
Heyy I would Like To Contribute ?

**Comment by schmelto** [comment]
Sure @bilalshaikh292 go ahead

**Comment by bilalshaikh292** [comment]
I Have Done It, Just Creating Pull Request In few Seconds.
