### ISSUE TITLE
[Feat]: automatic prettier action

### ISSUE THREAD

**Issue by schmelto** [schmelto/Portfolio#259]
### Feature request

https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/.github/workflows/prettier-lint-check.yml something like this

**Comment by ShivamMenda** [comment]
@schmelto If you could elaborate on how you want the workflow to happen, I can work on this.

**Comment by schmelto** [comment]
@ShivamMenda When files are merged the action should be triggered and format the files with commit message "style: format files" 
You can take a look here https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/.github/workflows/prettier-lint-check.yml

**Comment by ShivamMenda** [comment]
I can use the same yaml file I guess. I just need to change the trigger action. I can work on this.

**Comment by ShivamMenda** [comment]
@schmelto i see that you've got a format command already setup for prettier. I'll use the template you've provided and keep the trigger on a push to the main branch. I'll use npm run format along with the commit message as you want. You can assign this to me. I'll create the yaml file and then you can test it.

**Comment by schmelto** [comment]
I assigned you @ShivamMenda

**Comment by schmelto** [comment]
@ShivamMenda any update or do you need help?

**Comment by schmelto** [comment]
@ShivamMenda no problem.
