### ISSUE TITLE
[Bug]: Update Picture and Favicon

### ISSUE THREAD

**Issue by schmelto** [schmelto/Portfolio#260]
### What happened?

Update Picture to my new profile picture

https://github.com/schmelto.png can be used as link this will always get the latest github profile picture of my profile

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Other

**Comment by yr1404** [comment]
Working on it.

**Comment by schmelto** [comment]
> You want it to be changed for both favicon and about section, right?

Oh yes I completely forgot the favicon but yes that too.
