### ISSUE TITLE
[Docs]: update Picture in README.md

### ISSUE THREAD

**Issue by schmelto** [schmelto/Portfolio#263]
### Documentation

Update the demo picture in the README.md

**Comment by Jaishree2310** [comment]
can I take this issue?

**Comment by schmelto** [comment]
sure @Jaishree2310

**Comment by schmelto** [comment]
@Jaishree2310 do you need any help or further information or is everything clear?

**Comment by schmelto** [comment]
@Jaishree2310 any update on this topic? You still want to do this?

**Comment by harshsapra92** [comment]
Hi @schmelto can I take this issue?

**Comment by schmelto** [comment]
> Hi @schmelto can I take this issue?

Let wait until tomorrow, if @Jaishree2310 is not responding until then you can take this issue.
Hope this is fine for everyone.

**Comment by Jaishree2310** [comment]
> Hi @schmelto can I take this issue?

No, I will work on this within 1 or 2 days I will complete this. 
You can take another issue. 
Thanks.

**Comment by schmelto** [comment]
Ok than I will leave this assigned to @Jaishree2310

**Comment by Jaishree2310** [comment]
> @Jaishree2310 do you need any help or further information or is everything clear?

I've reviewed the existing demo picture in the README.md, and it appears to be the current updated version as per the mock-up. However, I would like to seek some clarification regarding the required updates. Could you please provide more specific details on what needs to be updated or any particular changes you have in mind for the demo picture?

**Comment by schmelto** [comment]
> > @Jaishree2310 do you need any help or further information or is everything clear?
> 
> I've reviewed the existing demo picture in the README.md, and it appears to be the current updated version as per the mock-up. However, I would like to seek some clarification regarding the required updates. Could you please provide more specific details on what needs to be updated or any particular changes you have in mind for the demo picture?

Sure. The mockup is a little bit outdated due the picture is changed. Otherwise the mockup should be quite the same. What I would suggest is using an updated version of the laptop and the phone due they look a little bit "old" maybe you can find something more appealing.

Hope this clarifies the issue a little bit more.

What also would be nice is to showcase the light and dark mode in the demo picture. So that there is the light mode on the laptop screen and the dark mode on the cell.

When I initially created the demo screen I went to a website and uploaded a screenshot of the website there and they generated the laptop and phone with the screenshot. But I cannot remember which site it was. Maybe you find something (when going with that please pay attention on the license so that the mockup image is free of use).

In case of any further questions please let me know. Thanks!

**Comment by Jaishree2310** [comment]
@schmelto, please review the demo pic I made using a MacBook Pro16 mock-up. Do you like this or i should change it?
I am sharing the ss of the pic I hope you find it better than the previous one. ☺️

![Demo](https://github.com/schmelto/Portfolio/assets/73012522/7e055833-2878-4018-92c0-5aa11392b2e1)

**Comment by Jaishree2310** [comment]
Also, I didn't find the portfolio in light mode if you have a light mode pic please share will make further changes.

**Comment by schmelto** [comment]
I like it @Jaishree2310 !
Where did you find it and is it free to use?

You can see the light ode version of the website when you are changing your system theme to light mode (in windows or macOS).

<img width="284" alt="image" src="https://github.com/schmelto/Portfolio/assets/30869493/ce928363-3d87-45e6-ae66-2bfb06026bab">

One other thing in the example above there is a "lets enhance" watermark.

**Comment by Jaishree2310** [comment]
I made it on Figma using free mock-up plugins.
yeah, I will remove that watermark thanks for noticing that.
