### ISSUE TITLE
[Style]: Formatting the braces `}` in About section

### ISSUE THREAD

**Issue by bharathkalyans** [schmelto/Portfolio#264]
### Documentation

Nice Portfolio website 😀, saw a small fix.

* Before formatting 👇🏻
<img width="1440" alt="Screenshot 2023-09-09 at 8 08 54 PM" src="https://github.com/schmelto/Portfolio/assets/49526472/cd20739e-1cf5-409b-a80a-4a05c529c195">

* After formatting 👇🏻
<img width="1440" alt="Screenshot 2023-09-09 at 8 09 14 PM" src="https://github.com/schmelto/Portfolio/assets/49526472/76b29b18-eae2-4903-9843-e0ae92d9cc2d">

**Comment by bharathkalyans** [comment]
Also, the code is not formatted properly! Needs a lot formatting.

**Comment by schmelto** [comment]
Nice catch do you want to work on this issue?

**Comment by bharathkalyans** [comment]
Yep Sure!

**Comment by schmelto** [comment]
I assigned you @bharathkalyans
