### ISSUE TITLE
[Feat]: add GH Action | first-interaction

### ISSUE THREAD

**Issue by schmelto** [schmelto/Portfolio#267]
### Feature request

https://github.com/actions/first-interaction

you can have a look here : https://github.com/schmelto/schmelto/blob/main/.github/workflows/greetings.yml

**Comment by harshsapra92** [comment]
Hi @schmelto I am taking this issue

**Comment by schmelto** [comment]
Sure I assigned you @harshsapra92

**Comment by harshsapra92** [comment]
@schmelto have fixed the issue: https://github.com/schmelto/Portfolio/pull/268
Please review
