### ISSUE TITLE
[Feat]: Adding border and shadow to the certificate section

### ISSUE THREAD

**Issue by priyagupta20044** [schmelto/Portfolio#339]
### Feature request

Hi, I want to work on this, please assign this to me with hacktoberfest label
The certificate section currently lacks visual emphasis, which makes it less appealing. To improve the aesthetics and user experience, I propose adding a border and shadow effect around the certificate section. This enhancement will not only make the certificate stand out but also improve its overall presentation.

Proposed Changes:
Add a solid or gradient border around the certificate section.
Implement a subtle shadow effect to create depth and make the section pop.
Benefits:

Improves visual hierarchy and user engagement.
Enhances the overall design of the certificate.

**Comment by schmelto** [comment]
Sounds great
