### ISSUE TITLE
[Bug]: H1 heading to big for smaller screens

### ISSUE THREAD

**Issue by schmelto** [schmelto/Portfolio#44]
![Screenshot_20210418_223802.jpg](https://user-images.githubusercontent.com/30869493/115160110-c8d6f000-a096-11eb-94e7-147ebe6a9d3f.jpg)

**Comment by PritamSarbajna** [comment]
hey @schmelto can I try to fix it ?

**Comment by schmelto** [comment]
> hey @schmelto can I try to fix it ?

Sure @PritamSarbajna

**Comment by PritamSarbajna** [comment]
# Hey @schmelto, 
If I can change the values inside translateY() then only it'll fix, so is there any way to define a variable inside them and then in any width calling required values ?


![Screenshot (162)](https://user-images.githubusercontent.com/90236635/181492826-11bc40e6-96f7-47a7-a2b3-4dec4caaaa77.png)
