### ISSUE TITLE
[Feat]: Your Portfolio don't attractive .

### ISSUE THREAD

**Issue by VasudevJaiswal** [schmelto/Portfolio#96]
@schmelto

1. Your portfolio not responsive
2. Not Looking cool
3. I think you should work on your portfolio

**Comment by VasudevJaiswal** [comment]
@schmelto 
1. Your portfolio not responsive 
2. Not Looking cool
3. I think you should work on your portfolio

**Comment by schmelto** [comment]
Hey @VasudevJaiswal thx for your feedback.

Could you tell me a little bit more about the points?

- What content in the portfolio is not responsive?

- could you tell me what do you think is not looking good and how can I improve this?

**Comment by schmelto** [comment]
Update: I've updated the issue description with your comment for easier tracking the issue

**Comment by schmelto** [comment]
@VasudevJaiswal just checking in could you tell me a little bit more about this issue :)

**Comment by VasudevJaiswal** [comment]
@schmelto 
Issue resolved

**Comment by VasudevJaiswal** [comment]
[Click here] (https://github.com/Jaidevstudio/support/issues/new/choose)

**Comment by schmelto** [comment]
Issues in other repositories are for me no place to promote and invite to a github organization. I will close this issue and delete the comment. Thanks for understanding.
